language: node_js
node_js:
  - "node"

addons:
  ssh_known_hosts:
  - git.epitech.eu

cache:
  directories:
    - node_modules

before_install:
  - npm prune

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa
  - ssh-add .travis/id_rsa
  - git remote add deploy git@git.epitech.eu:brice.lang-nguyen@epitech.eu/DEV_dashboard_2018
  - git push deploy --all
