language: node_js
node_js:
	- "node"

before_install:
	- npm install

script:
	- npm test

deploy:
	provider: heroku
	api_key:
		secure: KEY
	app: obscure-headland-59625
	on:
		repo: AsianPw/DEV_dashboard_2018