language: node_js
node_js:
  - "10.11.0"
  - "8.12.0"

addons:
  ssh_known_hosts:
  - git.epitech.eu

cache:
  directories:
    - node_modules

before_install:
  - npm prune

deploy:
  provider: heroku
  api_key:
    secure: $KEY
  app: obscure-headland-59625
  on:
    condition: $TRAVIS_TEST_RESULT == 0
    node: "10.11.0"
    branch: master
    repo: AsianPw/DEV_dashboard_2018

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa
  - ssh-add .travis/id_rsa
  - git remote add deploy git@git.epitech.eu:brice.lang-nguyen@epitech.eu/DEV_dashboard_2018
  - git push deploy --all
