language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

before_install:
  - npm prune

deploy:
  provider: heroku
  api_key:
    secure: "d2d4b7cb-cc79-4cd2-ae03-4635185a7f2e"
  app: obscure-headland-59625
  on:
    repo: AsianPw/DEV_dashboard_2018

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa
  - ssh-add .travis/id_rsa
  - git remote add deploy git@git.epitech.eu:brice.lang-nguyen@epitech.eu/DEV_dashboard_2018
  - git push deploy --all
